# Generated by Django 2.2.5 on 2020-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_value', models.PositiveIntegerField(default=0)),
                ('repetition', models.PositiveIntegerField(default=0)),
                ('ef', models.PositiveIntegerField(default=0)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('level_int', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('correct_answer', models.CharField(max_length=100)),
                ('distractor_one', models.CharField(max_length=100)),
                ('distractor_two', models.CharField(max_length=100)),
                ('distractor_three', models.CharField(max_length=100)),
                ('distractor_four', models.CharField(max_length=100)),
            ],
        ),
    ]
