# Generated by Django 2.2.5 on 2020-06-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='spanish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Spanish'),
        ),
        migrations.AddField(
            model_name='answered',
            name='spanish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Spanish'),
        ),
        migrations.AddField(
            model_name='answered',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
