# Generated by Django 2.2.5 on 2020-07-03 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_answered_last_review_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answered',
            name='review_time',
            field=models.DateTimeField(default=datetime.date(2020, 7, 3)),
        ),
    ]
