# Generated by Django 2.2.5 on 2020-07-05 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_auto_20200703_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answered',
            name='ef',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='answered',
            name='last_review_day',
            field=models.DateField(default=datetime.date(2020, 7, 5)),
        ),
        migrations.AlterField(
            model_name='answered',
            name='review_time',
            field=models.DateTimeField(default=datetime.date(2020, 7, 5)),
        ),
    ]
