# Generated by Django 2.2.5 on 2020-08-10 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_auto_20200705_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='construct_one',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='construct_three',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='construct_two',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='answered',
            name='ef',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='answered',
            name='last_review_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='answered',
            name='review_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
