# Generated by Django 2.2.5 on 2020-06-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('level_number', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, primary_key=True, serialize=False)),
                ('points_threshold', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spanish',
            fields=[
                ('spanish_phrase', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('english_translation', models.CharField(max_length=100)),
                ('previous', models.FloatField(default=1.0)),
                ('level_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Levels')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=0)),
                ('currentQuestion', models.IntegerField(default=0)),
                ('currentScore', models.IntegerField(default=0)),
                ('currentErrors', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Levels')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level_points', models.PositiveIntegerField(blank=True, default=0)),
                ('level_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Levels')),
            ],
            options={
                'unique_together': {('user', 'level_number')},
            },
        ),
    ]
