# Generated by Django 2.2.5 on 2020-07-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_playerscore_day_streak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
