# Generated by Django 2.2.5 on 2020-07-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='current_level_score',
            field=models.IntegerField(default=0),
        ),
    ]
