# Generated by Django 2.2.5 on 2020-07-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_playerscore_current_level_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='spanish',
            name='information',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
