# Generated by Django 2.2.5 on 2020-08-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_spanish_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='spanish',
            name='type',
            field=models.CharField(choices=[('verb', 'verb'), ('noun', 'noun'), ('pronoun', 'pronoun'), ('adjective/adverb', 'adjective/adverb'), ('question', 'question'), ('phrase', 'phrase')], default='', max_length=200),
        ),
    ]
