# Generated by Django 2.2.5 on 2020-08-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200809_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatus',
            name='review_game',
            field=models.BooleanField(default=False),
        ),
    ]
