# Generated by Django 2.2.5 on 2020-08-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_playerstatus_review_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatus',
            name='review_game',
            field=models.BooleanField(default=False),
        ),
    ]
