# Generated by Django 2.2.5 on 2020-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200828_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstatus',
            name='game',
        ),
        migrations.AddField(
            model_name='playerstatus',
            name='review_game',
            field=models.BooleanField(default=False),
        ),
    ]
