# Generated by Django 2.2.5 on 2020-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200828_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatus',
            name='game',
            field=models.CharField(default='', max_length=30),
        ),
    ]
