# Generated by Django 2.2.5 on 2020-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verbs',
            fields=[
                ('infinitive', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('yo', models.CharField(max_length=100)),
                ('tú', models.CharField(max_length=100)),
                ('usted_él_ella', models.CharField(max_length=100)),
                ('nosotros_nosotras', models.CharField(max_length=100)),
                ('vosotros_vosotras', models.CharField(max_length=100)),
                ('ustedes_ellos_ellas', models.CharField(max_length=100)),
            ],
        ),
    ]
