# Generated by Django 2.2.5 on 2020-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0004_auto_20200810_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepositions',
            fields=[
                ('spanish', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=100)),
            ],
        ),
    ]
