# Generated by Django 2.2.5 on 2020-08-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0005_prepositions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prepositions',
            new_name='Article',
        ),
    ]
